enhancement:
  - head-branch:
      - '^feat/'

bug:
  - head-branch:
      - '^fix/'

refactor:
  - head-branch:
      - '^refactor/'

# 🎨 UI / Components
ui:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/components/**'
          - 'src/layouts/**'
          - 'src/pages/**'

component:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/components/**'

# ✍️ Content & branding
content:
  - changed-files:
      - any-glob-to-any-file:
          - 'content/**'
          - 'data/**'
          - '**/*.md'
          - '**/*.json'

branding:
  - changed-files:
      - any-glob-to-any-file:
          - 'public/**'
          - 'assets/**'

# 📈 SEO / Analytics
seo:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/seo/**'
          - 'public/robots.txt'
          - 'public/sitemap.xml'

analytics:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/lib/analytics/**'

# ⚙️ Tech / Infra
ci-cd:
  - head-branch:
      - '^ci/'
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**/*'

setup:
  - changed-files:
      - any-glob-to-any-file:
          - 'config/**'
          - '*.config.*'
          - 'tsconfig.json'

# 📚 Documentation
documentation:
  - head-branch:
      - '^docs/'
  - changed-files:
      - any-glob-to-any-file:
          - 'README.md'
          - 'LICENSE'
          - 'docs/**'