name: Verify if PR corresponds to Conventional Commits & labels

on:
  pull_request_target:
    types: [ opened, reopened, edited, synchronize ]

jobs:
  validate-pr-title:
    name: Validate Pull Request title format
    if: github.event.action != 'synchronize'
    runs-on: ubuntu-24.04 # https://github.com/actions/runner-images?tab=readme-ov-file#available-images

    permissions:
      pull-requests: write # to post comments

    steps:
      - name: Log PR title
        env:
          # according to https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "Pull Request title: $TITLE"

      - name: Enforce Conventional Commits format
        uses: jef/conventional-commits-pr-action@v1

  auto-label-pr:
    name: Apply labels automatically
    if: github.event.action != 'edited'
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Label PR based on changed files
        uses: actions/labeler@v5
